version: 2
updates:
  - package-ecosystem: "all"
    directory: "../"
    schedule:
      interval: "every 1 minute"
    target-branch: "development"
    labels:
      - "dependencies"
    assignees:
      - "HassanAli-Ashlar"
    reviewers:
      - "HassanAli-Ashlar"

  allow:
    - dependency-type: "direct"
      update-type: "semver:patch"
    - dependency-type: "direct"
      update-type: "semver:minor"
    - dependency-type: "direct"
      update-type: "semver:major"
    - dependency-type: "all"
      update-type: "security"
